name: Release GO binaries

on:
  push:
    - "*"

jobs:
  releases-matrix:
    name: Release GO binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64]
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.19
        with:
          github_token: ${{ secrets.GO_RELEASER_GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "./cmd/dview"
          binary_name: "dview"
          ldflags: "-s -w"