name: Release GO binaries

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Go build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: git fetch --prune --unshallow
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Run Releaser
        uses: goreleaser/goreleaser-action@4
        with:
          version: latest
          args: release --clean
          workdir: ./cmd/dview
        env:
          GITHUB_TOKEN: ${{ secrets.GO_RELEASER_GITHUB_TOKEN }}